### ISSUE TITLE
Gulp optimize throws errors

### ISSUE THREAD

**Issue by afaur** [sonicparke/homework#1]
```
-> % node --version
v4.1.0
-> % npm --version
2.14.3
-> % gulp optimize
[22:04:46] Using gulpfile gulpfile.js
[22:04:46] Starting 'wiredep'...
[22:04:46] Wire up the bower css, js and our app js into the html.
[22:04:46] Starting 'clean-code'...
[22:04:46] Cleaning: ./.tmp/**/*.js,./build/**/*.html,./build/js/**/*.js
[22:04:46] Starting 'clean-fonts'...
[22:04:46] Cleaning: ./build/fonts/**/*.*
[22:04:46] Starting 'clean-images'...
[22:04:46] Cleaning: ./build/images/**/*.*
[22:04:46] Finished 'clean-fonts' after 17 ms
[22:04:46] Starting 'fonts'...
[22:04:46] Copying fonts.
[22:04:46] Finished 'clean-images' after 20 ms
[22:04:46] Starting 'images'...
[22:04:46] Copying images.
[22:04:46] gulp-imagemin: Minified 0 images
[22:04:46] Finished 'images' after 242 ms
[22:04:46] Finished 'clean-code' after 281 ms
[22:04:46] Starting 'templatecache'...
[22:04:46] Creating AngularJS $templateCache
[22:04:47] gulp-inject 9 files into index.html.
[22:04:47] Finished 'templatecache' after 171 ms
[22:04:47] Finished 'wiredep' after 574 ms
[22:04:47] Starting 'inject'...
[22:04:47] Wire up the css into the html, and call wiredep
[22:04:47] gulp-inject Nothing to inject into index.html.
[22:04:47] Finished 'inject' after 8.73 ms
[22:04:47] Finished 'fonts' after 437 ms
[22:04:47] Starting 'optimize'...
[22:04:47] Optimizing the javascript, css, html
[22:04:47] 'optimize' errored after 8.43 ms
[22:04:47] TypeError: $.useref.assets is not a function
    at Gulp.<anonymous> (homework/gulpfile.js:201:31)
    at module.exports (homework/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (homework/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (homework/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at homework/node_modules/gulp/node_modules/orchestrator/index.js:279:18
    at finish (homework/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at homework/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:52:4
    at f (homework/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/node_modules/once/once.js:17:25)
    at DestroyableTransform.onend (homework/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/index.js:31:18)
    at emitNone (events.js:72:20)
```

Was able to fix some of the issues but eventually got a stream based error after fixing `useref` following the migration notes, and changing filter to not call .restore as a function.

<img width="954" alt="changes" src="https://cloud.githubusercontent.com/assets/898523/12134829/f99890f8-b3f8-11e5-9890-94a8688b4015.png">

@sonicparke  Are you able to build this project successfully?

**Comment by sonicparke** [comment]
Ah, ok. Yeah I've seent that useref issue before. The API for useref changed a bit. However, I was able to run gulp optimize successfully on this so I'm not sure what the deal is there.

**Comment by sonicparke** [comment]
actually no. I can't run optimize. I hadn't tried that yet. I was just running `gulp serve-dev`.

**Comment by sonicparke** [comment]
This should be working now. Breaking changes with gulp-useref.
